spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: root


management:
  endpoints:
    web:
      exposure:
        include: "*"

